server:
  port: 8761

spring:
  application:
    name: test-springboot-naming-server
  main:
    allow-bean-definition-overrideing: true
  autoconfigure:
    exclude:
      "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
            
logging:
  file: logs/testspringboot-naming.log
  level:
    ROOT: info
    org:
      springframework: info
    cn:
      ryan:
        springboot: info

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false