server:
  port: 8761

spring:
  application:
    name: test-springboot-naming-service
  main:
    allow-bean-definition-overrideing: true
  autoconfigure:
    exclude:
      "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
            
logging:
  file: logs/testspringboot.log
  level:
    ROOT: warn
    org:
      springframework: warn
    cn:
      ryan:
        springboot: info

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false