server:
  port: 8761

spring:
  application:
    name: test-springboot-naming-service
  main:
    allow-bean-definition-overrideing: true
  autoconfigure:
    exclude:
      "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
            
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false