server:
  port: 8761

spring:
  application:
    name: test-springboot-naming-server
            
logging:
  file: logs/testspringboot-naming.log
  level:
    ROOT: warn
    org:
      springframework: warn
    cn:
      ryan:
        springboot: info

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false