server:
  port: 8765

spring:
  application:
    name: test-springboot-gateway-service
  main:
    allow-bean-definition-overrideing: true
  autoconfigure:
    exclude:
      "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
            
logging:
  file: logs/testspringboot.log
  level:
    ROOT: warn
    org:
      springframework: warn
    cn:
      ryan:
        springboot: info

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"