server:
  port: 8765

spring:
  application:
    name: test-springboot-gateway-server
            
logging:
  file: logs/testspringboot-gateway.log
  level:
    ROOT: warn
    org:
      springframework: warn
    cn:
      ryan:
        springboot: info

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"