server:
  port: 8888

test-service:
  testvalue: 1

management:
  endpoints:
    health:
      show-details: always
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: env

spring:
  application:
    name: test-springboot-main-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic: testkafka
  data:
    solr:
      host: "http://localhost:8983/solr"
  datasource:
    url:"jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username:root
    password:password
    driver-class-name:"com.mysql.jdbc.Driver"
      
logging:
  file: logs/testspringboot-main.log
  level:
    ROOT: warn
    org:
      springframework: warn
      hibernate: info
      apache:
        kafka: info
    cn:
      ryan:
        springboot: info

mybatis:
  typeAliasesPackage: "cn.ryan.springboot.model"
  mapperLocations: "classpath:mapper/*.xml"
  
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"