server:
  port: 9999

spring:
  application:
    name: test-springboot-assist-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  file: logs/testspringboot-assist.log
  level:
    ROOT: warn
    org:
      springframework: warn
    cn:
      ryan:
        springboot: info
            
#test-springboot-main-service:
#  ribbon:
#    listOfServers: "localhost:8888"

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"