server:
  port: 9999

spring:
  application:
    name: test-springboot-assist-service
  main:
    allow-bean-definition-overrideing: true
      
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG