server:
  port: 9999

spring:
  application:
    name: test-springboot-assist-service
  main:
    allow-bean-definition-overrideing: true
  autoconfigure:
    exclude:
      "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"

logging:
  file: logs/testspringboot-assist.log
  level:
    ROOT: info
    org:
      springframework: info
    cn:
      ryan:
        springboot: info
            
#test-springboot-main-service:
#  ribbon:
#    listOfServers: "localhost:8888"

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"