server:
  port: 9999

spring:
  application:
    name: test-springboot-assist-service
  main:
    allow-bean-definition-overrideing: true
  autoconfigure:
    exclude:
      "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
      
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
      
test-springboot-main-service:
  ribbon:
    listOfServers: "localhost:8888"